export default [
  {
    id: 1,
    cName: "Brute (Weak)",
    Strength: 2,
    Dexterity: -1,
    AttackModifier: ["STR", "STR"],
    DefenceModifier: ["STR", "STR"],
    MaxHP: 10,
    currentHP: 10,
    DamageDice: 6,
    Status: "",
    isInCombat: false,
  },
  {
    id: 2,
    cName: "Fighter (Weak)",
    Strength: 1,
    Dexterity: 1,
    AttackModifier: ["STR", "DEX"],
    DefenceModifier: ["STR", "DEX"],
    MaxHP: 10,
    currentHP: 10,
    DamageDice: 6,
    Status: "",
    isInCombat: false,
  },
  {
    id: 3,
    cName: "Rouge (Weak)",
    Strength: -1,
    Dexterity: 2,
    AttackModifier: ["DEX", "DEX"],
    DefenceModifier: ["DEX", "DEX"],
    MaxHP: 10,
    currentHP: 10,
    DamageDice: 6,
    Status: "",
    isInCombat: false,
  },
];
